[package]
name = "base64_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
